---
Title: "CS102 Activity 4"
Author: "Anton Geganzo"
date: "2024-02-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r 1}
library(dplyr)
library(stringr)
library(httr)
library(rvest)

URL <- 'https://arxiv.org/search/?query=%22pollution%22&searchtype=all&abstracts=show&order=-announced_date_first&size=50'

parse_url(URL)

Start <- proc.time()
Title <- NULL
Author <- NULL
Subject <- NULL
Abstract <- NULL
Meta <- NULL

pages <- seq(from = 0, to = 0, by = 2)

for( i in pages){
  
  tmp_url <- modify_url(url, query = list(Start = i))
  tmp_list <- read_html(tmp_url) %>% 
    html_nodes('p.list-title.is-inline-block') %>% 
    html_nodes('a[href^="https://arxiv.org/abs"]') %>% 
    html_attr('href')
  
for(j in 1:min(length(tmp_list), 10)){
    
  tmp_paragraph <- read_html(tmp_list[j])
    
    # Title
tmp_Title <- tmp_paragraph %>% html_nodes('h1.title.mathjax') %>% html_text(T)
tmp_Title <-  gsub('Title:', '', tmp_Title)
Title <- c(Title, tmp_Title)
    
    # Author
tmp_Author <- tmp_paragraph %>% html_nodes('div.authors') %>% html_text
tmp_Author <- gsub('\\s+',' ',tmp_Author)
tmp_Author <- gsub('Authors:','',tmp_Author) %>% str_trim
Author <- c(Author, tmp_Author)  
    
    # Subject
tmp_Subject <- tmp_paragraph %>% html_nodes('span.primary-subject') %>% html_text(T)
Subject <- c(Subject, tmp_Subject)
    
    # Abstract
tmp_Abstract <- tmp_paragraph %>% html_nodes('blockquote.abstract.mathjax') %>% html_text(T)
tmp_Abstract <- gsub('\\s+',' ',tmp_Abstract)
tmp_Abstract <- sub('Abstract:','',tmp_Abstract) %>% str_trim
Abstract <- c(Abstract, tmp_Abstract)
    
    # Meta
tmp_Meta <- tmp_paragraph %>% html_nodes('div.submission-history') %>% html_text
tmp_Meta <- lapply(strsplit(gsub('\\s+', ' ',tmp_Meta), '[v1]', fixed = T),'[',2) %>% unlist %>% str_trim
Meta <- c(Meta, tmp_Meta)
cat(j, "paper\n")
Sys.sleep(1)
    
  }
cat((i/50) + 1,'/ 9 page\n')
  
}
papers <- data.frame(Title, Author, Subject, Abstract, Meta)
end <- proc.time()
end - Start # Total Elapsed Time

# Export the result
save(papers, file = "Arxiv_Pollution.RData")
write.csv(papers, file = "Arxiv_Papers_on_Pollution.csv")
```


